[project]
name = "ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.2.0",
    "load-dotenv>=0.1.0",
    "openai>=2.14.0",
    "openai-agents>=0.6.4",
    "pydantic>=2.12.5",
    "pypdf>=6.6.2",
    "reportlab>=4.4.10",
    "requests>=2.32.5",
    "win10toast>=0.9",
    "winotify>=1.1.0",
]
